- name: Install Doppler CLI
  uses: dopplerhq/cli-action@v3
- name: Generate .env from Doppler secrets
  run: doppler secrets download --no-file --format env > .env
  env:
    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

